<a href="https://colab.research.google.com/github/Swarup012/Skin_disease_image_prediction/blob/master/Disease_PredictionML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
mytuple = ("Sandip","Swarup","Sarup")
print(mytuple)

('Sandip', 'Swarup', 'Sarup')


In [ ]:
from google.colab import files
uploaded = files.upload()


Saving genital-warts-8.jpeg to genital-warts-8.jpeg
Saving genital-warts-22.jpeg to genital-warts-22.jpeg
Saving genital-warts-28.jpeg to genital-warts-28.jpeg
Saving genital-warts-30.jpeg to genital-warts-30.jpeg
Saving genital-warts-31.jpeg to genital-warts-31.jpeg
Saving genital-warts-38.jpeg to genital-warts-38.jpeg
Saving genital-warts-41.jpeg to genital-warts-41.jpeg
Saving genital-warts-65.jpeg to genital-warts-65.jpeg
Saving genital-warts-66.jpeg to genital-warts-66.jpeg
Saving genital-warts-68.jpeg to genital-warts-68.jpeg
Saving genital-warts-83.jpeg to genital-warts-83.jpeg
Saving genital-warts-93.jpeg to genital-warts-93.jpeg
Saving genital-warts-106.jpeg to genital-warts-106.jpeg
Saving genital-warts-129.jpeg to genital-warts-129.jpeg
Saving warts-9.jpeg to warts-9.jpeg
Saving warts-10.jpeg to warts-10.jpeg
Saving warts-26.jpeg to warts-26.jpeg
Saving warts-37.jpeg to warts-37.jpeg
Saving warts-39.jpeg to warts-39.jpeg
Saving warts-common-4.jpeg to warts-common-4.jpeg
Savi

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving test_ML.csv to test_ML.csv


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving train.csv to train.csv


In [ ]:
import pandas as pd

df = pd.read_csv('test_ML.csv')
print(df.head(5000))
df


                                             image_path          label
0            test/Benign_tumors/dermatofibroma-103.jpeg  Benign_tumors
1      test/Benign_tumors/calcifying-epithelioma-7.jpeg  Benign_tumors
2            test/Benign_tumors/epidermal-cyst-147.jpeg  Benign_tumors
3            test/Benign_tumors/dermatofibroma-117.jpeg  Benign_tumors
4              test/Benign_tumors/porokeratosis-70.jpeg  Benign_tumors
...                                                 ...            ...
1541  test/Lupus/sle-03__ProtectWyJQcm90ZWN0Il0_Focu...          Lupus
1542          test/Lupus/lupus-chronic-cutaneous-1.jpeg          Lupus
1543  test/Lupus/2561__ProtectWyJQcm90ZWN0Il0_FocusF...          Lupus
1544  test/Lupus/2562__ProtectWyJQcm90ZWN0Il0_FocusF...          Lupus
1545                     test/Lupus/lupus-acute-11.jpeg          Lupus

[1546 rows x 2 columns]


image_path          label
0            test/Benign_tumors/dermatofibroma-103.jpeg  Benign_tumors
1      test/Benign_tumors/calcifying-epithelioma-7.jpeg  Benign_tumors
2            test/Benign_tumors/epidermal-cyst-147.jpeg  Benign_tumors
3            test/Benign_tumors/dermatofibroma-117.jpeg  Benign_tumors
4              test/Benign_tumors/porokeratosis-70.jpeg  Benign_tumors
...                                                 ...            ...
1541  test/Lupus/sle-03__ProtectWyJQcm90ZWN0Il0_Focu...          Lupus
1542          test/Lupus/lupus-chronic-cutaneous-1.jpeg          Lupus
1543  test/Lupus/2561__ProtectWyJQcm90ZWN0Il0_FocusF...          Lupus
1544  test/Lupus/2562__ProtectWyJQcm90ZWN0Il0_FocusF...          Lupus
1545                     test/Lupus/lupus-acute-11.jpeg          Lupus

[1546 rows x 2 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd

df = pd.read_csv('train.csv')

print(df.head())
df


                                          image_path          label
0         train/Benign_tumors/dermatofibroma-98.jpeg  Benign_tumors
1         train/Benign_tumors/dermatofibroma-38.jpeg  Benign_tumors
2  train/Benign_tumors/sebaceous-hyperplasia-24.jpeg  Benign_tumors
3       train/Benign_tumors/skin-tags-polyps-37.jpeg  Benign_tumors
4  train/Benign_tumors/sebaceous-hyperplasia-21.jpeg  Benign_tumors


image_path          label
0             train/Benign_tumors/dermatofibroma-98.jpeg  Benign_tumors
1             train/Benign_tumors/dermatofibroma-38.jpeg  Benign_tumors
2      train/Benign_tumors/sebaceous-hyperplasia-24.jpeg  Benign_tumors
3           train/Benign_tumors/skin-tags-polyps-37.jpeg  Benign_tumors
4      train/Benign_tumors/sebaceous-hyperplasia-21.jpeg  Benign_tumors
...                                                  ...            ...
13893  train/Lupus/lupus-bullous__ProtectWyJQcm90ZWN0...          Lupus
13894  train/Lupus/lupus-chilb__ProtectWyJQcm90ZWN0Il...          Lupus
13895  train/Lupus/discoid-lupus-19__ProtectWyJQcm90Z...          Lupus
13896        train/Lupus/lupus-chronic-cutaneous-18.jpeg          Lupus
13897       train/Lupus/lupus-chronic-cutaneous-104.jpeg          Lupus

[13898 rows x 2 columns]

In [ ]:
!pip install -q kaggle

In [ ]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"swarupbasu","key":"bf267ec7c48e9b3ab6cb2ec624ae4f27"}'}

In [ ]:
! mkdir ~/.kaggle

mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [ ]:
! cp kaggle.json ~/.kaggle/

In [ ]:
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
! kaggle datasets list

ref                                                         title                                               size  lastUpdated                 downloadCount  voteCount  usabilityRating  
----------------------------------------------------------  --------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------  
khushikyad001/water-pollution-and-disease                   Water Pollution & Disease                         148486  2025-04-03 15:46:19.363000           1447         23  1.0              
atharvasoundankar/chocolate-sales                           Chocolate Sales Data 📊🍫                            14473  2025-03-19 03:51:40.270000          20564        340  1.0              
adilshamim8/student-depression-dataset                      Student Depression Dataset                        467020  2025-03-13 03:12:30.423000          11471        166  1.0              
khushikyad001/air-pollution-in-china-2015-2025    

In [ ]:
import kagglehub

In [ ]:
path = kagglehub.dataset_download("pacificrm/skindiseasedataset")

print("Path to dataset files:", path)

100%|██████████| 1.36G/1.36G [00:16<00:00, 87.9MB/s]

Extracting files...


Path to dataset files: /root/.cache/kagglehub/datasets/pacificrm/skindiseasedataset/versions/6


In [ ]:
!kaggle datasets download -d pacificrm/skindiseasedataset

Dataset URL: https://www.kaggle.com/datasets/pacificrm/skindiseasedataset
License(s): CC0-1.0


In [ ]:
!unzip skindiseasedataset.zip

unzip:  cannot find or open skindiseasedataset.zip, skindiseasedataset.zip.zip or skindiseasedataset.zip.ZIP.


In [ ]:
from google.colab import drive

In [ ]:
drive.mount("/content/drive/")

Mounted at /content/drive/


In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/train.csv')
print(df.head())

                                          image_path          label
0         train/Benign_tumors/dermatofibroma-98.jpeg  Benign_tumors
1         train/Benign_tumors/dermatofibroma-38.jpeg  Benign_tumors
2  train/Benign_tumors/sebaceous-hyperplasia-24.jpeg  Benign_tumors
3       train/Benign_tumors/skin-tags-polyps-37.jpeg  Benign_tumors
4  train/Benign_tumors/sebaceous-hyperplasia-21.jpeg  Benign_tumors


In [ ]:
from google.colab import drive

In [ ]:
drive.mount("/content/drive/")

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).


In [ ]:
import pandas as pd

# Load your dataset (change path accordingly)
df = pd.read_csv('/content/drive/MyDrive/Maj_Project/train.csv')

# Show how many nulls are in each column before cleaning
print("Null values before cleaning:")
print(df.isnull().sum())

# Remove rows with any null values
df_cleaned = df.dropna()

# Show how many rows were removed
print(f"\nOriginal rows: {len(df)}")
print(f"Cleaned rows: {len(df_cleaned)}")
print(f"Removed {len(df) - len(df_cleaned)} rows with null values.")

# Optionally save the cleaned dataset
df_cleaned.to_csv('cleaned_skin_disease_dataset.csv', index=False)

print("\nCleaned dataset saved as 'cleaned_train.csv'")

Null values before cleaning:
image_path    0
label         0
dtype: int64

Original rows: 13898
Cleaned rows: 13898
Removed 0 rows with null values.

Cleaned dataset saved as 'cleaned_train.csv'


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13898 entries, 0 to 13897
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   image_path  13898 non-null  object
 1   label       13898 non-null  object
dtypes: object(2)
memory usage: 217.3+ KB


In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split


In [ ]:
import pandas as pd
import numpy as np


df = pd.read_csv('/content/drive/MyDrive/Maj_Project/train.csv')


labels = df.iloc[:, 0].values
images = df.iloc[:, 1:]

images = images.apply(pd.to_numeric, errors='coerce')
images = images.dropna()


images = images.astype('float32') / 255.0


labels = labels[images.index]

images = images.values.reshape(-1, 28, 28)


In [ ]:
import pandas as pd
import numpy as np


df = pd.read_csv('/content/drive/MyDrive/Maj_Project/test_ML.csv')


labels = df.iloc[:, 0].values
images = df.iloc[:, 1:]

images = images.apply(pd.to_numeric, errors='coerce')
images = images.dropna()


images = images.astype('float32') / 255.0


labels = labels[images.index]

images = images.values.reshape(-1, 28, 28)


In [ ]:
print(f"Number of samples: {len(images)}")


if len(images) == 0:
    print("No samples available. Please check your data cleaning steps.")
else:
    from sklearn.model_selection import train_test_split
    X_train, X_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42)



Number of samples: 0
No samples available. Please check your data cleaning steps.


In [ ]:
df.dtypes

image_path    object
label         object
dtype: object

In [ ]:

!pip install kaggle

In [ ]:
import os
import pandas as pd
from PIL import Image
from tqdm import tqdm

In [ ]:
def create_dataframe(data_dir):
    data = []
    classes = os.listdir(data_dir)
    for class_name in classes:
        class_path = os.path.join(data_dir, class_name)
        if not os.path.isdir(class_path):
            continue
        for img_name in os.listdir(class_path):
            img_path = os.path.join(class_path, img_name)
            data.append({'image_path': img_path, 'label': class_name})
    return pd.DataFrame(data)


In [ ]:
def clean_dataframe(df):

    df = df.drop_duplicates(subset='image_path')


    df = df.dropna()


    valid_images = []
    for idx, row in tqdm(df.iterrows(), total=len(df)):
        try:

            with Image.open(row['image_path']) as img:
                img.verify()
            valid_images.append(True)
        except:
            valid_images.append(False)

    df['is_valid'] = valid_images


    df = df[df['is_valid']].drop(columns=['is_valid'])


    df = df.reset_index(drop=True)

    df.fillna(0, inplace=True)

    # df = pd.get_dummies(df, columns=['category_column'], drop_first=True)
    labels = df.iloc[:, 0].values
    images = df.iloc[:, 1:].values

    return df

In [ ]:
train_dir = '/content/drive/MyDrive/Deep_Learning/SkinDisease/SkinDisease/train'
test_dir = '/content/drive/MyDrive/Deep_Learning/SkinDisease/SkinDisease/test'


train_df = create_dataframe(train_dir)
test_df = create_dataframe(test_dir)


print("Cleaning training data...")
train_df_clean = clean_dataframe(train_df)

print("Cleaning test data...")
test_df_clean = clean_dataframe(test_df)


print(f"\nClean train shape: {train_df_clean.shape}")
print(train_df_clean.head())

print(f"\nClean test shape: {test_df_clean.shape}")
print(test_df_clean.head())

Cleaning training data...


100%|██████████| 13898/13898 [01:04<00:00, 214.55it/s]


Cleaning test data...


100%|██████████| 1546/1546 [00:07<00:00, 203.27it/s]


Clean train shape: (13898, 2)
                                          image_path label
0  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
1  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
2  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
3  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
4  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne

Clean test shape: (1546, 2)
                                          image_path label
0  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
1  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
2  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
3  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
4  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne


In [ ]:
import shutil

drive_train_dir = '/content/drive/MyDrive/Deep_Learning/SkinDisease/SkinDisease/cleanednew_train'
drive_test_dir = '/content/drive/MyDrive/Deep_Learning/SkinDisease/SkinDisease/cleanednew_test'

os.makedirs(drive_train_dir, exist_ok=True)
os.makedirs(drive_test_dir, exist_ok=True)

In [ ]:
def copy_clean_images(df, target_dir):
    for label in df['label'].unique():
        label_dir = os.path.join(target_dir, label)
        os.makedirs(label_dir, exist_ok=True)

    for idx, row in tqdm(df.iterrows(), total=len(df)):
        src = row['image_path']
        dst = os.path.join(target_dir, row['label'], os.path.basename(src))
        try:
            shutil.copy(src, dst)
        except Exception as e:
            print(f'Error copying {src}: {e}')


copy_clean_images(train_df_clean, drive_train_dir)
copy_clean_images(test_df_clean, drive_test_dir)

100%|██████████| 1546/1546 [00:25<00:00, 60.86it/s]


In [ ]:
train_df_clean.to_csv('/content/drive/MyDrive/Deep_Learning/SkinDisease/SkinDisease/cleanednew_train.csv', index=False)
test_df_clean.to_csv('/content/drive/MyDrive/Deep_Learning/SkinDisease/SkinDisease/cleanednew_test.csv', index=False)


In [1]:

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

train_df_cleaned = pd.read_csv('/content/drive/MyDrive/Deep_Learning/SkinDisease/SkinDisease/cleanednew_train.csv')
test_df_cleaned = pd.read_csv('/content/drive/MyDrive/Deep_Learning/SkinDisease/SkinDisease/cleanednew_test.csv')

print(train_df_cleaned.head())
print(test_df_cleaned.head())

Mounted at /content/drive
                                          image_path label
0  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
1  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
2  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
3  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
4  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
                                          image_path label
0  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
1  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
2  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
3  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne
4  /content/drive/MyDrive/Deep_Learning/SkinDisea...  Acne


#Data Preprocessing

In [2]:
#training datsets
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [3]:
training_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/Deep_Learning/SkinDisease/SkinDisease/cleanednew_train',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 13898 files belonging to 22 classes.


In [4]:
testing_set = tf.keras.utils.image_dataset_from_directory(
    '/content/drive/MyDrive/Deep_Learning/SkinDisease/SkinDisease/cleanednew_test',
    labels="inferred",
    label_mode="categorical",
    class_names=None,
    color_mode="rgb",
    batch_size=32,
    image_size=(128, 128),
    shuffle=True,
    seed=None,
    validation_split=None,
    subset=None,
    interpolation="bilinear",
    follow_links=False,
    crop_to_aspect_ratio=False,
)

Found 1546 files belonging to 22 classes.


In [5]:
training_set

<_PrefetchDataset element_spec=(TensorSpec(shape=(None, 128, 128, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 22), dtype=tf.float32, name=None))>

In [ ]:
for x,y in training_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[192.21289   156.21289   142.21289  ]
   [184.76562   149.73242   135.41016  ]
   [195.04883   161.39258   148.36133  ]
   ...
   [167.26953   135.26953   123.58203  ]
   [162.07227   128.01172   115.947266 ]
   [164.17383   128.17383   114.17383  ]]

  [[192.6875    156.6875    140.6875   ]
   [196.58203   163.40039   146.46094  ]
   [189.17578   156.21094   139.13086  ]
   ...
   [161.0625    129.07617   114.03516  ]
   [165.36914   132.43164   117.2168   ]
   [161.0625    128.0625    111.       ]]

  [[194.11133   161.11133   145.09961  ]
   [196.71094   163.71094   146.71094  ]
   [189.42188   158.42188   138.42188  ]
   ...
   [167.0918    136.0918    118.0918   ]
   [163.10742   132.10742   113.98242  ]
   [163.6875    132.6875    112.6875   ]]

  ...

  [[178.02344   143.02344   114.03516  ]
   [175.46289   139.46289   115.46289  ]
   [178.48438   142.48438   119.29297  ]
   ...
   [165.42969   137.14844   116.99219  ]
   [163.07617   132.07617   112.11133  ]
   [1

In [6]:
for x,y in testing_set:
    print(x,x.shape)
    print(y,y.shape)
    break

tf.Tensor(
[[[[2.40000000e+01 2.30000000e+01 1.90000000e+01]
   [2.86406250e+01 2.82656250e+01 2.75156250e+01]
   [2.91640625e+01 2.92421875e+01 3.27656250e+01]
   ...
   [9.57890625e+01 1.07789062e+02 1.31789062e+02]
   [8.68046875e+01 1.01804688e+02 1.24804688e+02]
   [9.39687500e+01 1.09968750e+02 1.32968750e+02]]

  [[2.96015625e+01 2.43515625e+01 1.87265625e+01]
   [3.01328125e+01 2.68828125e+01 2.17578125e+01]
   [3.07578125e+01 2.66328125e+01 2.45625000e+01]
   ...
   [9.36875000e+01 1.05687500e+02 1.29687500e+02]
   [8.90234375e+01 1.04023438e+02 1.27023438e+02]
   [8.94218750e+01 1.05421875e+02 1.28421875e+02]]

  [[3.35000000e+01 2.45000000e+01 1.75000000e+01]
   [3.83593750e+01 3.13593750e+01 2.33593750e+01]
   [3.71953125e+01 3.01953125e+01 2.41953125e+01]
   ...
   [9.67343750e+01 1.08734375e+02 1.32734375e+02]
   [9.17578125e+01 1.06757812e+02 1.29757812e+02]
   [9.05625000e+01 1.06562500e+02 1.29562500e+02]]

  ...

  [[9.24375000e+01 9.94375000e+01 1.15437500e+02]
   [8

In [ ]:
cnn =

In [ ]:
model = Sequential()